### ISSUE TITLE
Packages are never picked up

### ISSUE THREAD

**Issue by craigagnew** [HedgehogDevelopment/SitecorePackageDeployer#13]
Hey all,

Having a strange issue with SPD where, having installed the module, the job seems to run but never finds my *.update packages.

`
ManagedPoolThread #15 13:12:11 INFO  Job started: Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage
ManagedPoolThread #15 13:12:11 INFO  Setting installer state to InstallingPackage
ManagedPoolThread #15 13:12:11 INFO  Setting installer state to Ready
ManagedPoolThread #15 13:12:11 INFO  Job ended: Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage (units processed: )
ManagedPoolThread #18 13:13:11 INFO  Job started: Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage
ManagedPoolThread #18 13:13:11 INFO  Setting installer state to InstallingPackage
ManagedPoolThread #18 13:13:11 INFO  Setting installer state to Ready
ManagedPoolThread #18 13:13:11 INFO  Job ended: Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage (units processed: )
ManagedPoolThread #4 13:14:11 INFO  Job started: Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage
ManagedPoolThread #4 13:14:11 INFO  Setting installer state to InstallingPackage
ManagedPoolThread #4 13:14:11 INFO  Setting installer state to Ready
ManagedPoolThread #4 13:14:11 INFO  Job ended: Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage (units processed: )
`

Anyone seen similar happen before?

Any help appreciated.

Craig

**Comment by cturano** [comment]
Hi Craig,
     That is odd. I haven't seen that before. I have a couple of suggestions:

1) Verify the setting for the Sitecore Package Deployer folder. The default is $(dataFolder)\SitecorePackageDeployer. If you moved it make sure the identity running the website has read access.
2) If you delete the SPD folder and reset IIS, is it re-created at startup? If not, there could be permission issues.
3) Can you reproduce this locally? If so, can you step through the code to determine if it is looking in the right place and/or seeing the files?

Thanks

Charlie

**Comment by craigagnew** [comment]
Hi Charlie,

Finally getting round to picking this back up. 

1. This setting is correct, yep.
2. The SPD folder does not get created at startup. Permissions are wide open. 
3. I'll try bringing down the source and stepping through.

Any other ideas would be appreciated in the meantime.

Thanks,
Craig

**Comment by craigagnew** [comment]
After some digging around in debug it turns out SPD was creating & looking for packages in C:\{$dataFolder}\SitecorePackageDeployer. This is despite the setting in the .config file being set to the following:

`<setting name="SitecorePackageDeployer.PackageSource" value="$(dataFolder)\SitecorePackageDeployer"/>`

Setting this to the explicit path and some app pool recycling done the trick. Have you any idea why the relative path wouldn't work? Does it need to be prefixed with tilde (i.e. "~\$(dataFolder\SPD")?

**Comment by cturano** [comment]
Hi Craig,
    We use the Sitecore API Settings.GetSetting() to retrieve the value of that field. I'm not sure why that value didn't work since this is the default value. What is the value of the <sc.variable> dataFolder set to?

Thanks

Charlie

**Comment by craigagnew** [comment]
Hi Charlie,

The value for this is: 

`<sc.variable name="dataFolder" set:value="/App_Data" />`

Thanks,
Craig

**Comment by craigagnew** [comment]
An update on this one. 

I've tried with varying permutations of the "dataFolder" setting to no avail. Sitecore itself manages to create the "log", "diagnostics" and "Submit Queue" folders inside the correct dataFolder directory in the website root but SPD still insists on breaking out and creating my "$(dataFolder)\SPD" in the C: drive. 

Have also tried on a blank install of Sitecore and same thing happens.

**Comment by eltrixo** [comment]
Hi,

I am having similar issues. To answer your questions @cturano :

1. Have set the value to "$(dataFolder)\PackageDeployer". DataFolder is set to the default App_Data config for an Azure deployment. ShowConfig.aspx lists the package source as "D:\home\site\wwwroot\App_Data\PackageDeployer"
2. The directory is being created if I delete it.
3. Same issue is happening locally (i.e. can't seem to see update package). I have not brought down the code to debug yet.

Pat

**Comment by cturano** [comment]
Hi Pat,
    We use the Sitecore Job Agent to run a job to poll that folder. Are you sure the job is running? You should see messages in the log every minute. I have seen situations where the configs were patched to tell to job agent to run with a much longer interval.
    Since the folder is being created, I suspect the initialization steps of the deployer are running.
    Since the problem is happening locally, it should be relatively easy to hook up the debugger and see if the job is looking in the right location or if it is not seeing the files. It is possible that the files permissions are preventing the identity the website is running under from seeing the files in the folder.

Please let us know what you find.

Thanks

Charlie

**Comment by craigagnew** [comment]
Update on this one. 

Managed to successfully integrate SPD by changing the "dataFolder" variable to the full path of the directory and packages were from then on picked up by SPD automatically. Implications for our CD process but works.
