### ISSUE TITLE
Sitecore 9 Support

### ISSUE THREAD

**Issue by craigagnew** [HedgehogDevelopment/SitecorePackageDeployer#21]
Hi,

I've noticed SPD is listed as supporting Sitecore 9 in one of the most recent commits to the Readme. Is this definitely the case? 

I've implemented SPD on a Sitecore 9 solution to be met by unhandled exceptions comlpaining about a missing method in Sitecore.Update.Installer.XmlEntrySerializer. 

> Message: Method not found: 'Void Sitecore.Update.Installer.XmlEntrySerializer.Serialize(System.Collections.Generic.List`1<Sitecore.Update.Installer.ContingencyEntry>, System.IO.Stream)'.

This is down to the fact that this method signature in Sitecore.Update.dll in Sitecore 9 has changed to be an `IEnumerable<ContingencyEntry>` instead of `List<ContingencyEntry>`. 

I'm hoping I have crossed wires and there's a straightforward answer to this one. Any help appreciated in any case. 

Thanks,
Craig

**Comment by cturano** [comment]
Hi Craig,
    Can you tell us how you got that error? I'm running SPD on a Sitecore 9 environment without issues.

Thanks

Charlie

**Comment by craigagnew** [comment]
Hey Charlie,

I managed to get this error by running SPD 1.8 thinking it was 1.10. And now I feel silly. 🤦‍♂️ 

Deployed with 1.10 and all working now. Your re-assurance that it defo works made me review my setup so thanks for the help!

Cheers,
Craig
