### ISSUE TITLE
Issue in Installing Team Development for Sitecore

### ISSUE THREAD

**Issue by AnuKrithikaS** [HedgehogDevelopment/SitecorePackageDeployer#23]
Hello,
I am trying to install the latest version of Team Development for Sitecore (TDS 5.7.0.24) . My visual studio version is 2017 and using Dot Net framework 4.5.2. I am facing issue in installing TDS. When I am trying to finish the installation, below VSIX Installer is popped up and appears to be frozen for long time without showing any progress.

![tds_issue](https://user-images.githubusercontent.com/44606099/47714912-34793880-dc64-11e8-9b48-75c3c175e034.PNG)

Please let me know if there is any way to resolve this issue.

Thanks,
Anu

**Comment by SaintSkeeta** [comment]
This issue is unrelated to the Sitecore Package Installer. 
It is about Hedgehog's TDS Classic tool, so I suggest emailing support@hhogdev.com to try to resolve this instead.
