### ISSUE TITLE
Package fails on Sitecore 8.1

### ISSUE THREAD

**Issue by mithun** [HedgehogDevelopment/SitecorePackageDeployer#4]
I'm trying to use this with Sitecore 8.1 and see this exception:

```
[InvalidOperationException: Could not get pipeline: getFieldValue (domain: )]
   Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +460
   Sitecore.Data.Fields.Field.GetValue(Boolean allowStandardValue, Boolean allowDefaultValue, Boolean allowFallbackValue, Boolean allowInheritValue, Boolean allowInnerValue) +384
   Sitecore.Data.Fields.Field.get_Value() +27
   Sitecore.Data.Items.DeviceItem.MatchesQueryString() +116
   Sitecore.Data.Items.DeviceItem.get_IsValid() +18
   Sitecore.Data.Items.DeviceItem.FindBestMatch(Database database, HttpContextBase httpContext) +124
   Sitecore.Data.Items.DeviceItem.ResolveDevice(Database database, HttpContextBase httpContext) +283
   Sitecore.Pipelines.HttpRequest.DeviceResolver.Process(HttpRequestArgs args) +293
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +445
   Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +488
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +92
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165
```

The Sitecore.Kernel.dll version is 8.1.0.5297.

Please advise

**Comment by cturano** [comment]
Hi Mithun,
    We just released a new version of the package deployer (1.3) that we tested with Sitecore 8.1. Are you running this one?
Can you tell us a bit more about the exception and how you are getting it?

Thanks

Charlie

Charles Turano
Sitecore Architect
Office: (631)676-2186 x220
Skype: Charles.Turano

Hedgehog Development, LLC.http://www.hhogdev.com/
Productshttp://www.hhogdev.com/products.aspx | Serviceshttp://www.hhogdev.com/solutions.aspx  | Twitterhttps://twitter.com/hhogdev | Facebookhttps://www.facebook.com/hhogdev | Linkedinhttps://www.linkedin.com/company/hedgehog-development | Jobshttp://www.hhogdev.com/careers/jobopenings.aspx

**Comment by mithun** [comment]
Yes, I am using v1.3.

The .update package was not installing via the installer wizard. It said "package installed", but I couldn't see any files being updated on the file-system.

In our environment, we are attempting to automate most of the provisioning/deployment of Sitecore, so I just ended up deploying the files from the '.update' package manually.

I am troubleshooting some more now, and will let you know what I find.

**Comment by mithun** [comment]
Nevermind. The issue I am seeing is not related to SitecorePackageDeployer. Sorry for the trouble

**Comment by cturano** [comment]
NP.  Please let me know if you need anything else.

Thanks

Charlie

Charles Turano
Sitecore Architect
Office: (631)676-2186 x220
Skype: Charles.Turano

Hedgehog Development, LLC.http://www.hhogdev.com/
Productshttp://www.hhogdev.com/products.aspx | Serviceshttp://www.hhogdev.com/solutions.aspx  | Twitterhttps://twitter.com/hhogdev | Facebookhttps://www.facebook.com/hhogdev | Linkedinhttps://www.linkedin.com/company/hedgehog-development | Jobshttp://www.hhogdev.com/careers/jobopenings.aspx
